Repository joshxfi/trackAsOne, pull requests merged in 2022-04, with the labels that each got.

#58 release: v1.0.8 - beta
  next-seo-config.js
  package.json
  pages/create.tsx
  pages/join.tsx
  pages/room.tsx
  src/components/Button/Button.tsx
  src/components/EmptyModal.tsx
  src/components/Error.tsx
  src/components/Home/Invitation.tsx
  src/components/Home/RoomLabel.tsx
  src/components/ImageFill.tsx
  src/components/Input.tsx
  src/components/Modal.tsx
  src/components/Navbar.tsx
  src/components/Room/Info.tsx
  src/components/Room/InviteUser.tsx
  src/components/Room/Task.tsx
  src/components/Room/TaskFields.tsx
  src/components/Room/UserRequest.tsx
  src/components/RoomInput.tsx
  src/components/index.ts
  src/utils/constants.ts
  src/utils/functions.ts
  styles/tailwind.css
  yarn.lock
Labels: enhancement, bugfix, chore

#66 move page types to root
  pages/404.tsx
  pages/_app.tsx
  pages/_offline.tsx
  pages/about.tsx
  pages/contact.tsx
  pages/create.tsx
  pages/index.tsx
  pages/join.tsx
  pages/room.tsx
  types/page.d.ts
Labels: refactor

#63 Fix/radio buttons alignment
  pages/room.tsx
Labels: bugfix

#68 refactor footer
  src/components/Footer.tsx
  src/utils/constants.ts
Labels: refactor

#69 refactor footer & add links
  src/components/Footer.tsx
  src/utils/constants.ts
Labels: refactor

#72 release: v1.0.8.1
  firestore.rules
  package.json
  pages/code-of-conduct.tsx
  pages/join.tsx
  pages/privacy-policy.tsx
  pages/the-project.tsx
  src/components/Badges.tsx
  src/components/Footer.tsx
  src/components/Layout.tsx
  src/components/Markdown.tsx
  src/components/Navbar.tsx
  src/components/Room/Info.tsx
  src/components/index.ts
  src/utils/constants.ts
  src/utils/contents.ts
  tailwind.config.js
  types/models.d.ts
  yarn.lock
Labels: documentation, chore
